MODEL:
  TYPE: litv2
  NAME: litv2_base_384
  DROP_PATH_RATE: 0.5
  OFFSET_LR_MULTI: 0.01
  PRETRAINED: ckpt_epoch_best.pth
  LIT:
    EMBED_DIM: 128
    DEPTHS: [ 2, 2, 18, 2 ]
    NUM_HEADS: [ 4, 8, 16, 32 ]
    ALPHA: 0.9
    LOCAL_WS: [ 0, 0, 2, 1 ]
DATA:
  IMG_SIZE: 384
  NUM_WORKERS: 10
  BATCH_SIZE: 128
  DATA_PATH: /home/datasets/imagenet
  DATASET: imagenet
TRAIN:
  EPOCHS: 30
  WARMUP_EPOCHS: 5
  WEIGHT_DECAY: 1e-8
  BASE_LR: 2e-05
  WARMUP_LR: 2e-08
  MIN_LR: 2e-07
TEST:
  CROP: False