MODEL:
  TYPE: litv2
  NAME: litv2_base
  DROP_PATH_RATE: 0.5
  OFFSET_LR_MULTI: 0.01
  LIT:
    EMBED_DIM: 128
    DEPTHS: [ 2, 2, 18, 2 ]
    NUM_HEADS: [ 4, 8, 16, 32 ]
    ALPHA: 0.9
    LOCAL_WS: [ 0, 0, 2, 1 ]
DATA:
  NUM_WORKERS: 10
  BATCH_SIZE: 128
  DATA_PATH: /home/datasets/imagenet
  DATASET: imagenet